# Generated by Django 5.0.6 on 2024-05-27 06:41

import problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problems/', validators=[problems.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
