# Generated by Django 5.0.6 on 2024-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_content_problem_description_problem_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('lowest', '최하'), ('low', '하'), ('medium', '중'), ('high', '상'), ('highest', '최상')], default='medium', max_length=10),
        ),
    ]
