# Generated by Django 5.0.6 on 2024-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subject',
            field=models.CharField(default='기타', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('최하', '최하'), ('하', '하'), ('중', '중'), ('상', '상'), ('최상', '최상')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problems/'),
        ),
    ]
