# Generated by Django 5.0.6 on 2024-05-27 14:46

import django.db.models.deletion
import problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_subject_alter_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='file',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('최하', '최하'), ('하', '하'), ('중', '중'), ('상', '상'), ('최상', '최상')], default='중', max_length=10),
        ),
        migrations.CreateModel(
            name='ProblemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='problems/', validators=[problems.models.validate_file_extension])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='problems.problem')),
            ],
        ),
    ]
